export const Config = {
    InternetTxt : "No Internet Connection",
    noConnection:"NO INTERNET CONNECTION",
    CheckIntrenet:"Please Check Your Network Connection",
    tryAgain:"and Try Again",
    retry:"Retry",
    PlayTxt : "Play Your Game Any Time, Any where !!!....",
    AlreadyUser : "Already Registered User?",
    LoginTxt : "Login",
    bold : "Ubuntu-Bold",
    regular : "Ubuntu-Regular",
    light : "Ubuntu-Light",
    medium : "Ubuntu-Medium",
    SignHeading : "Enter Signup Details",
    otpVerfication :  "OTP Verification",
    entername : "Enter Name ",
    enterPhone : "Enter Mobile Number  ",
    enterPassword : "Enter 4 digit Passcode ",
    enterConfirmPassword : "Re-Enter Passcode ",
    termsTxt : "Terms & Conditions",
    signupTxt : "Sign Up",
    enterotp:"Enter OTP",
    verifyOtp: "Verify OTP",
    verifysendmsg:"Enter 6 Digit code that has been sent to your registered mobile umber ending with last Four Digits +91*******3939!",
    verify:"Verify",
    resendOtp:"Resend OTP",
    successotp:"OTP Sent Successfully!",
    verifying:"Verifying...",
    otpVerifiedSuccess:"OTP Verified successfully!",
    enterlogindetails:"Enter Login Details",
    login : "Log in",
    newuser:"New User?",
    createaccount:"Create an Account",
    enterpasscode: "Enter Passcode",
    forgotpassword: "Forgot Passcode",
    next:"Next",
    forgotpass : "Forgot Passcode",
    loginwithotp:"Login with OTP",
    verifyotp : "Verify OTP",
    tournaments: "Tournaments",
    viewall:"View All",
    leagues:"Leagues",
    loginSuccessmsg:"Logged in Successful!",
   incorrectUser: "Incorrect User Name (or) Passcode",
   otp:"OTP",
   passcode:"Passcode",
   close: "Close",
  entercorrectmobile: "*Enter registered mobile number ! "


    
    
    
    

}